Ingredient.create(name:"ketchup")
Ingredient.create(name:"mayonnaise")
Ingredient.create(name:"mustard")
Ingredient.create(name:"relish")
Ingredient.create(name:"pickles")
Ingredient.create(name:"whole chicken")
Ingredient.create(name:"sausage")
Ingredient.create(name:"veggie burgers")
Ingredient.create(name:"ground beef")
Ingredient.create(name:"deli meat")
Ingredient.create(name:"whole milk")
Ingredient.create(name:"buttermilk")
Ingredient.create(name:"hot dogs")
Ingredient.create(name:"cheddar cheese")
Ingredient.create(name:"sour cream")
Ingredient.create(name:"greek yogurt")
Ingredient.create(name:"half and half")
Ingredient.create(name:"butter")
Ingredient.create(name:"shredded cheese")
Ingredient.create(name:"orange juice")
Ingredient.create(name:"smoked salmon")
Ingredient.create(name:"ham")
Ingredient.create(name:"tofu pups")
Ingredient.create(name:"beer")
Ingredient.create(name:"wine")
Ingredient.create(name:"red wine vinegar")
Ingredient.create(name:"olive oil")
Ingredient.create(name:"salt")
Ingredient.create(name:"pepper")
mere = Shopper.create(name: "Meredith")
james = Shopper.create(name: "James")
