Item.create(name:"ketchup")
Item.create(name:"mayonnaise")
Item.create(name:"mustard")
Item.create(name:"relish")
Item.create(name:"pickles")
Item.create(name:"whole chicken")
Item.create(name:"sausage")
Item.create(name:"veggie burgers")
Item.create(name:"ground beef")
Item.create(name:"deli meat")
Item.create(name:"whole milk")
Item.create(name:"buttermilk")
Item.create(name:"hot dogs")
Item.create(name:"cheddar cheese")
Item.create(name:"sour cream")
Item.create(name:"greek yogurt")
Item.create(name:"half and half")
Item.create(name:"butter")
Item.create(name:"shredded cheese")
Item.create(name:"orange juice")
Item.create(name:"smoked salmon")
Item.create(name:"ham")
Item.create(name:"tofu pups")
Item.create(name:"beer")
Item.create(name:"wine")
Item.create(name:"red wine vinegar")
Item.create(name:"olive oil")
Item.create(name:"salt")
Item.create(name:"pepper")
mere = Shopper.create(name: "Meredith")
james = Shopper.create(name: "James")
List.create(name: "test", shopper_id: james.id)
List.create(name: "party", shopper_id: mere.id)
